### ISSUE TITLE
output is graphviz.files.Source object

### ISSUE THREAD

**Issue by sinancetinkaya** [mgedmin/objgraph#47] opened 2019-12-27 18:59 UTC
In the document it says

```
>>> x = []
>>> y = [x, [x], dict(x=x)]
>>> import objgraph
>>> objgraph.show_refs([y], filename='sample-graph.png')
Graph written to ....dot (... nodes)
Image generated as sample-graph.png
```

But I get this instead, there is no image file
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.10.2
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
x = []
y = [x, [x], dict(x=x)]
import objgraph
objgraph.show_refs([y], filename='sample-graph.png')
Out[5]: <graphviz.files.Source at 0x58aa170>

```
graphviz is installed

```
pip3 install graphviz
Requirement already satisfied: graphviz in d:\program files\python\python37-32\lib\site-packages (0.13.2)
```

**Comment by mgedmin** [comment] 2019-12-30 08:49
Ah yes, this is the feature where if you used a graphical ipython/jupyter console, you'd see the graph inline: https://github.com/mgedmin/objgraph/pull/28

Clearly it doesn't work that well in a text-only console.

Two things seem broken to me:
- the detection of ipython's interactive console is supposed to check if this is a terminal-only console and do nothing special in that case.
- an explicit filename=... argument should override this, but it doesn't (and I see where the bug is!)

Regarding the first, could you please report what the following returns in your ipython shell?

    get_ipython().__class__.__name__

Regarding the second, I've just committed a fix.  Can you please try git master?

**Comment by sinancetinkaya** [comment] 2019-12-30 11:56
the first:
![image](https://user-images.githubusercontent.com/2675655/71580872-9c9b0700-2b13-11ea-9366-e94919c95847.png)

the second:
```
>>> y = [x, [x], dict(x=x)]
>>> import objgraph
>>> objgraph.show_refs([y], filename='sample-graph.png')
Graph written to D:\Temp\objgraph-hu58dy85.dot (4 nodes)
Image renderer (dot) not found, not doing anything else
```

**Comment by mgedmin** [comment] 2019-12-30 12:11
Oh, you _are_ using Jupyter!

Maybe the inline graphs don't work in the web-based console?  I think the original contributor was using qtconsole.

Or maybe the problem is just that you don't have graphviz itself installed:

> Image renderer (dot) not found, not doing anything else

**Comment by sinancetinkaya** [comment] 2019-12-30 12:25
Yes, I tested **get_ipython().__class__.__name__** in jupyter.
But updated objgraph was tested in python console of pycharm

**Comment by mgedmin** [comment] 2019-12-30 13:04
> Yes, I tested get_ipython().__class__.__name__ in jupyter.
> But updated objgraph was tested in python console of pycharm

It would be helpful to also know what `get_ipython().__class__.__name__` produces in the pycharm console too.  (I'm assuming that's what you copied and pasted the `Out[5]: <graphviz.files.Source at 0x58aa170>` bit in the original post?)

> See the first post graphviz is installed.

You have the [`graphviz` Python library](https://pypi.org/project/graphviz/), but not [`graphviz` the actual program that lays out and draws graphs](https://www.graphviz.org/download/).

Also, the programs installed (specifically `dot.exe`) need to be on your PATH so that objgraph can find it.  I don't recall if graphviz has an installer that can take care of this, or if you need to update your PATH manually from the control panel.

**Comment by sinancetinkaya** [comment] 2019-12-30 13:45
I didn't know this would require this much work... I no longer need it but here it is:
> It would be helpful to also know what `get_ipython().__class__.__name__` produces in the pycharm console too. 
```
get_ipython().__class__.__name__
Out[6]: 'PyDevTerminalInteractiveShell'
```


> You have the [`graphviz` Python library](https://pypi.org/project/graphviz/), but not [`graphviz` the actual program that lays out and draws graphs](https://www.graphviz.org/download/).
> 
> Also, the programs installed (specifically `dot.exe`) need to be on your PATH so that objgraph can find it. I don't recall if graphviz has an installer that can take care of this, or if you need to update your PATH manually from the control panel.

I will do that when I need objgraph again.

**Comment by mgedmin** [comment] 2019-12-30 14:24
> PyDevTerminalInteractiveShell

Thank you, that'll let me improve the autodetection code to avoid trying to put inline graphics in environments where they don't work!

**Closed by mgedmin** 2019-12-30 14:24 UTC
